version: '3'

services:
  mindMapBackend:
    container_name: mind_map_backend
    image: renasustek/mind-map-backend
    ports:
      - '8080:8080'
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/mind_map?useSSL=false&serverTimezone=UTC&useUnicode=yes&characterEncoding=UTF-8
  # MySQL
  db:
    container_name: mysql_mindmap
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: mind_map
      MYSQL_USER: renas
      MYSQL_PASSWORD: ustek
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - './docker/db/sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql'

